services:
  frontend:
    build:
      context: ./shopping-app-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - categories-api
      - orders-api
    environment:
      - NEXT_PUBLIC_CATEGORIES_API_URL=http://localhost:5000/api/categories
      - NEXT_PUBLIC_ORDERS_API_URL=http://localhost:5001/api/orders
    networks:
      - shopping-network

  categories-api:
    build:
      context: ./CategoriesAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CategoriesDb;User=sa;Password=password123;
    depends_on:
      - sqlserver
    networks:
      - shopping-network

  orders-api:
    build:
      context: ./orders-api
      dockerfile: Dockerfile
    ports:
      - "5001:3001"
    depends_on:
      - mongodb
    networks:
      - shopping-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - shopping-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - shopping-network

networks:
  shopping-network:
    driver: bridge

volumes:
  sqlserverdata:
  mongodbdata:
